from django.shortcuts import render
from .models import *
from live import models
# Create your views here.
def index(request):
    print(request)
    return render(request,'home.html')
def intern(request):
      return render(request,'internship.html')
def webin(request):
      return render(request,'webinar.html')
def contacts(request):
      if(request.method=='POST'):
            fname=request.POST.get('fname')
            email=request.POST.get('email')
            phone=request.POST.get('phone')
            message=request.POST.get('message')
            print(fname,email,phone,message)  
            ins=models.Contacts(name=fname,email=email,phone=phone,message=message)   
            ins.save()
            print("Saved")
      return render(request,'contact.html')
def recomm(request):
      return render(request,'recom.html')
def demo(c,b):
    op=Livedata.objects.filter(type=b).values()
    o1={}
    a=[]
    for i in op:
        o1['key1']=i['keytopic1'].split('*')
        o1['key2']=i['keytopic2'].split('*')
        o1['key3']=i['projectexp'].split('*')
        o1['jobroles']=i['jobroles'].split('*')
        o1['suitable']=i['suitable'].split('*')
    for i in o1['key3']:
        a.append(i.split('+'))
    o1['key3']=a
    print(o1)
    '''o1['key1']=op['keytopic1'].split('*')'''
    return render(c,'index.html',{'value1':op,'value2':o1})

def java(request):
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'java')
def adjava(request):
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'adjava')
def c(request):
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'c')
def ac(request): #c++
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'ac')
def python(request):
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'python')
def mern(request):
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'mern')
def django(request):
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'django')
def app(request):#kotlin
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'app')
def cs(request):#c Sharp
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'cs')
def plc(request):
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'plc')
def epsa(request):#electrical power system Analysis
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'epsa')
def matlab(request):
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'matlab')
def microcont(request):#microcontroller
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'microcont')
def neteng(request):#network engineering
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'neteng')
def amicrocont(request):#advanced microcontroller
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'amicrocont')
def netsec(request):#network security
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'netsec')
def ethical(request):#ethical hacking
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'ethical')
def ds(request):#data science
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'ds')
def dsde(request):#data science and data engineering
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'dsde')
def dsr(request):#data science using r
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'dsr')
def ml(request):#machine learning
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'ml')
def mlp(request):#machine learning using python
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'mlp')
def mlr(request):#machine learning using r
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'mlr')
def bc(request):#block chain
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'bc')
def ai(request):#artifical intelligence
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'ai')
def rpa(request):#RPA
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'rpa')
def robo(request):#robotics
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'robo')
def IOT(request):
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'iot')
def nlp(request):
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'nlp')
def tdprinting(request):#3 d printing
      if(request.method=='POST'):
            lname=request.POST.get('lname')
            email=request.POST.get('email')
            no=request.POST.get('no')
            country=request.POST.get('country')
            state=request.POST.get('state')
            print(lname,email,no,country,state)  
            inst=models.Enquiry(lname=lname,email=email,no=no,country=country,state=state)   
            inst.save()
            print("Saved")
      return demo(request,'tdprinting')
