# Generated by Django 4.1 on 2023-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2080)),
                ('des1', models.TextField()),
                ('intro_img', models.CharField(max_length=2080)),
                ('duration', models.IntegerField()),
                ('name2', models.CharField(max_length=2080)),
                ('des2', models.TextField()),
                ('objective', models.TextField()),
                ('keytopic1', models.TextField()),
                ('keytopic2', models.TextField()),
                ('scope', models.TextField()),
                ('range1', models.IntegerField()),
                ('range2', models.IntegerField()),
                ('projectexp', models.TextField()),
            ],
        ),
    ]
