# Generated by Django 4.1 on 2023-06-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='jobroles',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='livedata',
            name='suitable',
            field=models.TextField(default='1'),
        ),
    ]
