# Generated by Django 4.1 on 2023-06-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_livedata_jobroles_livedata_suitable'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='type',
            field=models.CharField(default='java', max_length=2080),
        ),
    ]
